name: diceware
description: A cryptographically secure passphrase generation method

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.4+35

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter_svg: ^0.17.3+1
  flutter_svg: ^0.18.0
  http: 0.12.0+3
  flutter_launcher_icons: 0.7.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  image: last_version
#  xml: last_version

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dice-1.svg
    - assets/dice-2.svg
    - assets/dice-3.svg
    - assets/dice-4.svg
    - assets/dice-5.svg
    - assets/dice-6.svg
    - assets/dictionaries/alphanumeric.json.gz
    - assets/dictionaries/alt_english.json.gz
    - assets/dictionaries/ascii.json.gz
    - assets/dictionaries/catalan.json.gz
    - assets/dictionaries/dutch.json.gz
    - assets/dictionaries/eff.json.gz
    - assets/dictionaries/esperanto.json.gz
    - assets/dictionaries/eyeware.json.gz
    - assets/dictionaries/german.json.gz
    - assets/dictionaries/polish.json.gz
    - assets/dictionaries/spanish.json.gz
    - assets/dictionaries/std_english.json.gz
    - assets/dictionaries/swedish.json.gz
    - assets/dictionaries/japanese.json.gz

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true