name: Diceware CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ internal ]
  pull_request:
    branches: [ internal ]
jobs:
  build:
    name: Build Appbundle
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "${{ secrets.PROPS_FILE }}" > key.properties.asc
          echo "${{ secrets.KEYSTORE }}" > publish_keystore.asc
          gpg -d --passphrase "${{ secrets.PROPS_FILE_PASSWORD }}" --batch key.properties.asc > android/key.properties
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASS }}" --batch publish_keystore.asc > android/app/publish_keystore
      - set-env: JSON_KEY_DATA="${{ secrets.JSON_KEY_DATA }}"
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.5'
      - run: flutter pub get
      - run: flutter test
      #- uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      #    working-directory: diceware
      #    script: |
      #      flutter run test/widget_test.dart
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'internal'
          subdirectory: 'android'
          skip-tracking: 'true'
    #  uses: ncipollo/release-action@v1
    #  with:
    #            tag: "latest"
    #    artifacts: "build/app/outputs/bundle/release/app-release.aab"
    #    token: ${{ secrets.GITHUB_TOKEN }}
