name: Diceware CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build APK
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - run: |
        echo "${{ secrets.PROPS_FILE }}" > key.properties.asc
        echo "${{ secrets.KEYSTORE }}" > publish_keystore.asc
        gpg -d --passphrase "${{ secrets.PROPS_FILE_PASSWORD }}" --batch key.properties.asc > diceware/android/key.properties
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASS }}" --batch publish_keystore.asc > diceware/android/app/publish_keystore
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.5'
    - run: flutter pub get
      working-directory: diceware
    #- uses: reactivecircus/android-emulator-runner@v2
    #  with:
    #    api-level: 29
    #    working-directory: diceware
    #    script: |
    #      flutter run test/widget_test.dart 
    - uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'beta'
        subdirectory: 'diceware/android'
        skip-tracking: 'true'
    #- name: Create a Release APK
    #  uses: ncipollo/release-action@v1
    #  with:
    #            tag: "latest"
    #    artifacts: "build/app/outputs/apk/debug/*.apk"
    #    token: ${{ secrets.TOKEN_NAME }}
